# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80ee33768a83d6ef08ad279af8e05c953e82903e7ec77257b554b28e01f98f104aad4eb22bf09e9b335068c6adb12749c48c6a5059f513f7a6278202c3b8229a

test:
  secret_key_base: 9159bda02643cb537460a7b2456d9f4094b14fdf90a62689ee649faf13e4c8de0036ebc7f6a772a5f0b9c4acea3060cf602354155bdd1b3b0858e15893631dd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
